run-name: Release of Rotion by @${{github.actor}}
on:
  push:
    tags: 
      - 'rotion-v*'


jobs:
  release-rotion:
    # Only run this job on tags that start with "v" (e.g. "v1.2.3")
    if: startsWith(github.ref, 'refs/tags/rotion-v')
    # Run this job on all supported operating systems
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./rotion
    defaults:
      run:
        # Use the `rotion` folder as the working directory
        working-directory: ./rotion

    # Define the matrix of operating systems
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: apt-update
        # Only run this step on Ubuntu
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt-get update

      - name: autoremove
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt autoremove

      - name: Install libarchive rpm on Linux
        # Only run this step on Ubuntu
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt-get install libarchive-tools rpm

      - name: Release Electron app
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          yarn install  # Instala as dependências do app
          yarn run build  # Compila o app
          npx electron-builder --publish always --config ./electron-builder.yml
          